# Generated by Django 3.0.6 on 2021-02-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribemodel',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscribemodel',
            name='updated_date',
        ),
    ]
