# Generated by Django 3.0.3 on 2021-02-01 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
